version: '2.1'

services:
  site:
    image: jekyll/builder
    command: jekyll serve --force_polling
    volumes:
      - ./:/srv/jekyll
    ports:
      -  4000:4000
#      - 35729:35729
#      -  3000:3000
#      -    80:4000
